#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      RELEASE:
        description: 'RELEASE Version'
        required: true
#       default: 'latest'
        default: '2026.07.27-1746'
      BRANCH:
        description: 'feeds branch'
        required: true
      PACKAGE_NAME:
        description: 'package name'
        required: true
      BASE_FEED:
        description: 'source branch'
        required: false
        default: 'coolsnowwolf\/lede'
      LUCI_FEED:
        description: 'LuCI branch'
        required: false
        default: 'coolsnowwolf\/luci.git;openwrt-25.12'
      gcc13:
        description: '使用 GCC 13'
        required: true
        default: true
        type: boolean
      gcc14:
        description: '使用 GCC 14'
        required: false
        default: false
        type: boolean
        
env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  CCACHE: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: false
  UPLOAD_IPK: false
  TZ: Asia/Shanghai

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          include:
          - arch: aarch64_generic
            target: openwrt-sdk-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-rockchip-armv8_gcc-14.2.0_musl.Linux-x86_64

          - arch: arm_cortex-a15_neon-vfpv4
            target: openwrt-sdk-armsr-armv7_gcc-13.3.0_musl_eabi.Linux-x86_64
            gcc14: openwrt-sdk-armsr-armv7_gcc-14.2.0_musl_eabi.Linux-x86_64

          - arch: arm_cortex-a9_vfpv3-d16
            target: openwrt-sdk-mvebu-cortexa9_gcc-13.3.0_musl_eabi.Linux-x86_64
            gcc14: openwrt-sdk-mvebu-cortexa9_gcc-14.2.0_musl_eabi.Linux-x86_64

          - arch: i386_pentium-mmx
            target: openwrt-sdk-x86-geode_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-x86-geode_gcc-14.2.0_musl.Linux-x86_64

          - arch: loongarch64_generic
            target: openwrt-sdk-loongarch64-generic_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-loongarch64-generic_gcc-14.2.0_musl.Linux-x86_64

          - arch: mips_24kc
            target: openwrt-sdk-ath79-generic_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-ath79-generic_gcc-14.2.0_musl.Linux-x86_64

          - arch: mipsel_24kc
            target: openwrt-sdk-ramips-mt7621_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-ramips-mt7621_gcc-14.2.0_musl.Linux-x86_64

          - arch: powerpc_464fp
            target: openwrt-sdk-apm821xx-nand_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-apm821xx-nand_gcc-14.2.0_musl.Linux-x86_64

          - arch: powerpc_8540
            target: openwrt-sdk-mpc85xx-p1010_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-mpc85xx-p1010_gcc-14.2.0_musl.Linux-x86_64

          - arch: riscv64_generic
            target: openwrt-sdk-sifiveu-generic_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-sifiveu-generic_gcc-14.2.0_musl.Linux-x86_64

          - arch: x86_64
            target: openwrt-sdk-x86-64_gcc-13.3.0_musl.Linux-x86_64
            gcc14: openwrt-sdk-x86-64_gcc-14.2.0_musl.Linux-x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons signify-openbsd squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        if [[ "${{ inputs.gcc14 }}" == true ]]; then
          wget -q https://github.com/Internet1235/compile/releases/download/${{ github.event.inputs.RELEASE }}/${{ matrix.gcc14 }}.tar.xz
          tar -xf ${{ matrix.gcc14 }}.tar.xz
          mv ${{ matrix.gcc14 }} openwrt-sdk
        else
          wget -q https://github.com/Internet1235/compile/releases/download/${{ github.event.inputs.RELEASE }}/${{ matrix.target }}.tar.xz
          tar -xf ${{ matrix.target }}.tar.xz
          mv ${{ matrix.target }} openwrt-sdk
        fi
        ln -sf /workdir/openwrt-sdk $GITHUB_WORKSPACE/openwrt-sdk

    - name: Cache
      if: env.CCACHE == 'true'
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: ${{ github.workspace }}/openwrt-sdk

    - name: Load custom feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt-sdk
        sed -i 's/coolsnowwolf\/packages/Internet1235\/packages;${{ github.event.inputs.BRANCH }}/g' feeds.conf.default
        if [[ -n "${{ inputs.BASE_FEED }}" ]]; then
          sed -i 's/coolsnowwolf\/lede/${{ github.event.inputs.BASE_FEED }}/g' feeds.conf.default
        fi
        if [[ -n "${{ inputs.LUCI_FEED }}" ]]; then
          sed -i 's/coolsnowwolf\/luci.git;openwrt-25.12/${{ github.event.inputs.LUCI_FEED }}/g' feeds.conf.default
        fi
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: cd openwrt-sdk && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt-sdk && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt-sdk/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt-sdk/.config
        chmod +x $DIY_P2_SH
        cd openwrt-sdk
        $GITHUB_WORKSPACE/$DIY_P2_SH
    
    - name: Generate build keys
      run: |
        cd openwrt-sdk
        signify-openbsd -G -n -c 'DO NOT USE - OpenWrt packages feed CI' -p key-build.pub -s key-build.sec
        echo "$(cat key-build.sec)" >> key-build

    - name: Download package
      id: package
      run: |
        cd openwrt-sdk
        make defconfig
        make package/${{ github.event.inputs.PACKAGE_NAME }}/download -j1 V=s
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt-sdk
        echo -e "$(nproc) thread compile"
        make package/${{ github.event.inputs.PACKAGE_NAME }}/check -j$(nproc) V=s && make package/${{ github.event.inputs.PACKAGE_NAME }}/{clean,compile} package/index -j$(nproc) V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        cd .. && cp openwrt-sdk/bin/packages/${{ matrix.arch }}/packages/* .
        cp openwrt-sdk/bin/packages/${{ matrix.arch }}/luci/* .

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt-sdk/bin

    - name: 创建packages.zip
      id: zip
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_IPK == 'true'
      run: |
        cd openwrt/bin/packages/mipsel_24kc
        zip -r packages.zip *
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate ipk tag
      id: tag
      if: steps.zip.outputs.status == 'success' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload ipk to release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ipk ${{ steps.tag.outputs.release_tag }}
        tag_name: ipk-${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: openwrt/bin/packages/mipsel_24kc/packages.zip

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag1
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      if: steps.tag1.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag1.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Upload packages directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ matrix.arch }}-${{ github.sha }}-packages
        path: |
          Packages
          Packages.*
          *.ipk

    - name: Upload logs directory
      uses: actions/upload-artifact@main
      if: ${{ !cancelled() }}
      with:
        name: ${{ matrix.arch }}-${{ github.sha }}-logs
        path: openwrt-sdk/logs
